"""Add missing user fields

Revision ID: 64562e2d1dec
Revises: 86ddcc96ee9e
Create Date: 2025-10-04 22:23:22.497308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64562e2d1dec'
down_revision = '86ddcc96ee9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_columns = [col['name'] for col in inspector.get_columns('user')]
    
    with op.batch_alter_table('user', schema=None) as batch_op:
        if 'first_name' not in existing_columns:
            batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=True, server_default='Unknown'))
        if 'surname' not in existing_columns:
            batch_op.add_column(sa.Column('surname', sa.String(length=50), nullable=True, server_default='Unknown'))
        if 'other_names' not in existing_columns:
            batch_op.add_column(sa.Column('other_names', sa.String(length=100), nullable=True))
        if 'date_of_birth' not in existing_columns:
            batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        if 'national_id' not in existing_columns:
            batch_op.add_column(sa.Column('national_id', sa.String(length=50), nullable=True, server_default='Unknown'))
        if 'phone_number' not in existing_columns:
            batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=True, server_default='Unknown'))
        if 'alt_phone_number' not in existing_columns:
            batch_op.add_column(sa.Column('alt_phone_number', sa.String(length=15), nullable=True))
        if 'physical_address' not in existing_columns:
            batch_op.add_column(sa.Column('physical_address', sa.String(length=200), nullable=True, server_default='Unknown'))
        if 'district' not in existing_columns:
            batch_op.add_column(sa.Column('district', sa.String(length=50), nullable=True, server_default='Unknown'))
        if 'city_town' not in existing_columns:
            batch_op.add_column(sa.Column('city_town', sa.String(length=100), nullable=True, server_default='Unknown'))
        if 'license_type' not in existing_columns:
            batch_op.add_column(sa.Column('license_type', sa.String(length=50), nullable=True, server_default='Unknown'))
        if 'fishing_method' not in existing_columns:
            batch_op.add_column(sa.Column('fishing_method', sa.String(length=50), nullable=True, server_default='Unknown'))
        if 'fishing_location' not in existing_columns:
            batch_op.add_column(sa.Column('fishing_location', sa.String(length=50), nullable=True, server_default='Unknown'))
        if 'hear_about' not in existing_columns:
            batch_op.add_column(sa.Column('hear_about', sa.String(length=50), nullable=True, server_default='Unknown'))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('user_username_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['national_id'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('user_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('hear_about')
        batch_op.drop_column('fishing_location')
        batch_op.drop_column('fishing_method')
        batch_op.drop_column('license_type')
        batch_op.drop_column('city_town')
        batch_op.drop_column('district')
        batch_op.drop_column('physical_address')
        batch_op.drop_column('alt_phone_number')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('national_id')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('other_names')
        batch_op.drop_column('surname')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
