"""Add payment tracking fields to License table

Revision ID: 874166701a9d
Revises: 64562e2d1dec
Create Date: 2025-10-05 13:12:39.705890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874166701a9d'
down_revision = '64562e2d1dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('license', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Unknown'::character varying"))
        batch_op.alter_column('surname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Unknown'::character varying"))
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('national_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False,
               existing_server_default=sa.text("'Unknown'::character varying"))
        batch_op.alter_column('physical_address',
               existing_type=sa.VARCHAR(length=200),
               nullable=False,
               existing_server_default=sa.text("'Unknown'::character varying"))
        batch_op.alter_column('district',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Unknown'::character varying"))
        batch_op.alter_column('city_town',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'Unknown'::character varying"))
        batch_op.alter_column('license_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Unknown'::character varying"))
        batch_op.alter_column('fishing_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Unknown'::character varying"))
        batch_op.alter_column('fishing_location',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Unknown'::character varying"))
        batch_op.alter_column('hear_about',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Unknown'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('hear_about',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Unknown'::character varying"))
        batch_op.alter_column('fishing_location',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Unknown'::character varying"))
        batch_op.alter_column('fishing_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Unknown'::character varying"))
        batch_op.alter_column('license_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Unknown'::character varying"))
        batch_op.alter_column('city_town',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'Unknown'::character varying"))
        batch_op.alter_column('district',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Unknown'::character varying"))
        batch_op.alter_column('physical_address',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               existing_server_default=sa.text("'Unknown'::character varying"))
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True,
               existing_server_default=sa.text("'Unknown'::character varying"))
        batch_op.alter_column('national_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('surname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Unknown'::character varying"))
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Unknown'::character varying"))

    with op.batch_alter_table('license', schema=None) as batch_op:
        batch_op.drop_column('bank_name')
        batch_op.drop_column('payment_date')
        batch_op.drop_column('payment_reference')
        batch_op.drop_column('payment_amount')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
